project:
  type: website
  output-dir: docs

website:
  title: "Sijan"
  site-url: https://sijan14.github.io/sijan_portfolio/
  description: "Sijan's portfolio and blog"
  page-footer: 
    center: "Copyright 2024, Md Allama Ikbal Sijan" 
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - posts.qmd

format:
  html:
    theme: Lux
    css: styles.css
    toc: true
    page-layout: full
    embed-resources: true
    allow-raw-html: true
    smooth-scroll: true

editor: visual

