---
title: "About"
page-navigation: true
---

## 🐸 About Me

Hey there! I’m Sijan, a Ph.D. candidate in Industrial-Organizational Psychology with a concentration in Data Science at Montclair State University. In other words, I’m passionate about people, data, and making workplaces better for everyone.

#### 🧠 My Research

I blend psychology with cutting-edge data science techniques to create psychometrically valid, reliable assessment tools. By leveraging natural language processing (NLP) and large language models (LLMs), I design psychometrically robust tools to predict key organizational metrics like job satisfaction, engagement, and turnover. My most recent work focuses on examining the validity, predictive bias, and risk of adverse impact of AI-based assessment tools and scoring systems. I also explore topics like team decision-making, delay discounting, and biases and heuristics.

#### 🧩 Beyond the Academia

When I’m not diving into data or teaching statistics as an adjunct professor, I’m leading initiatives and workshops for METRO, SIO NYC, and Eagle I/O, empowering I/O students and professionals. I’ve also worked with organizations like JUST Capital and City Bank, helping them make data-driven decisions to enhance their workforce strategies.

## 🎓 Education

-   *Doctor of Philosophy, Industrial-Organizational Psychology (Concentration: Data Science)*\
    Montclair State University \| 2022 - 2026

-   *Graduate Certificate in Advanced Quantitative Methods*\
    Montclair State University \| 2022 - 2025

-   *Master of Arts, Industrial-Organizational Psychology*\
    Montclair State University \| 2022 - 2024

-   *Bachelor of Arts, Global Management & Psychology*\
    Earlham College \| 2018 - 2022

## 🧑🏽‍💻 Experience

-   *Doctoral Research Assistant*, **Montclair State University** \| August 2022 - Present

-   *Adjunct Professor*, **Montclair State University** \| September 2024 - Present

-   *Co-Director of Education*, [METRO](https://metroapppsych.com/) \| October 2023 - Present

-   *Founding Board Member*, [SIONYC](https://www.linkedin.com/company/sionyc/) \| September 2023 - May 2024

-   *President & Consultant*, [Eagle I.O](https://www.linkedin.com/company/eagle-i-o/posts/?feedView=all) \| September 2023 - May 2024

-   *Research Intern*, [JUST Capital](https://justcapital.com/) \| May 2023 - August 2023

-   *Graduate Assistant*, [Center for Writing Excellence](https://www.montclair.edu/center-for-writing-excellence/) \| September 2022 - May 2023

-   *Consulting & Data Analytics Extern*, **Paragon One** \| June 2022 - September 2022

-   *HR Reporting Intern*, [City Bank Limited](https://www.citybankplc.com/home) \| May 2021 - August 2021

## 🎙️Presentations

-   **Sijan, M.**, Bixter, M. T. (under review). Using BERT embeddings to predict job satisfaction and turnover intention. *Journal of Computational Social Science.*

-   **Sijan, M.**, Echevarria, N., Herrera, I., Hollow, H., & Bixter, M. T. (under review). *Evaluating the validity, reliability, and fairness of AI-based assessments in personnel selection: A systematic review \[*Poster\]. Society for Industrial and Organizational Psychology Annual Conference, New Orleans, Louisiana, United States.

-   Crowley, L., **Sijan, M.** (under review). *When problems predict profits: Insights from anonymous Glassdoor reviews* \[Poster\]. Society for Industrial and Organizational Psychology Annual Conference, New Orleans, Louisiana, United States.

-   Sijan, M. (Co-chair), Belwalkar, B. B. (Co-chair) & Mracek, D. (Discussant) (2025). Power of NLP and LLMs: Turning I/O Research and Practice into a Textual Adventure \[Symposium\]. Society for Industrial and Organizational Psychology Annual Conference, Denver, CO, United States.\*

-   Huynh, C., Elfeki, Y., Sijan, M. (2025). Modeling Latent Constructs in SJT Using Pseudo-Factor Analysis \[Poster\]. Society for Industrial and Organizational Psychology Annual Conference, Denver, CO, United States.\*

-   **Sijan, M.**, Bixter, M. T. (2025). *Testing the latent structure of a measure of delay of gratification* \[Poster\]. 2025 Montclair State

    University Graduate Research Symposium, Montclair, NJ, United States.

-   Sijan, M., Bixter, M. T. (2024). Using NLP to Predict Job Satisfaction and Turnover Intention \[Poster Presentation\]. The Psychonomic Society Annual Meeting, New York, NY, United States.

-   Bragger, J., Helisch, R., Buczek, E., Hunt, L., Sijan, M., Abbasi, F., Filstein, T., Myszko, Z., Sherman, C., & Lakusta, L. (2024). Neurodiversity in Leadership: The Relationship Between Theory of Mind and Leadership Roles, and Possible Implications for Neurodivergent Workers \[Presentation\]. Interdisciplinary Perspectives on Leadership Symposium, Thessaloniki, Greece.

-   Sijan, M., Kramer, M. (Co-Chair), Kulas, J. (Co-Chair), Helisch, R., Lancuna, L., Defabiis, M., Hunt, L., Notari, K., (2024). Unlocking the value of IO Psychology Student Consulting in Higher Education \[Panel Presentation\]. Society for Industrial and Organizational Psychology Annual Conference, Chicago, IL, United States.

-   Elfeki, Y., Huynh, C., Sijan, M., Salter, N. P. (2024). An Exploration of Masculinity and Femininity Perceptions Across Monoracial and Biracial Identities using StyleGAN Imagery \[Symposium\]. Society for Industrial and Organizational Psychology Annual Conference, Chicago, IL, United States.

-   **Sijan, M.**, Bixter, M. T. (2024). *Using NLP to predict job satisfaction and turnover intention* \[Poster\]. 2024 Montclair State University Graduate Research Symposium, Montclair, NJ, United States.

-   Hunt, L., Bragger, J., Kubu, G., Abbasi, F., & Sijan, M. (2024). Leading the Goals' Rush: How leadership mindsets make all the difference \[Poster Presentation\]. Society for Industrial and Organizational Psychology Annual Conference, Chicago, IL, United States.

-   **Sijan M.** (2022). Perception of Trust Based on Parenthood Status \[Poster Presentation\]. 94th Annual MPA (Midwestern Psychological Association) Conference. Chicago, IL, United States.
